-- Trickplay: sprite-sheet paths for seek-bar preview thumbnails.
-- Generated by the generate-trickplay background task after scan.
ALTER TABLE media_items ADD COLUMN IF NOT EXISTS trickplay_path TEXT;
ALTER TABLE episodes    ADD COLUMN IF NOT EXISTS trickplay_path TEXT;
